version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samtest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pevh5e7ik8ti"
s3_prefix = "samtest"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
